#ifndef DS_CONTROLLER_BACKLIGHT_H
#define DS_CONTROLLER_BACKLIGHT_H

#define DS_CONTROLLER_BACKLIGHT_TOP_OFF 1u
#define DS_CONTROLLER_BACKLIGHT_TOP_ON 2u
#define DS_CONTROLLER_BACKLIGHT_BOTTOM_OFF 3u
#define DS_CONTROLLER_BACKLIGHT_BOTTOM_ON 4u

#endif
